
spring.application.name=demo

spring.datasource.url=jdbc:mariadb://localhost:3306/demo
spring.datasource.username=demo
spring.datasource.password=demo2024
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

security.jwt.secret-key=pGv5S9h+F3z/7A9+t4lqB5yF8kE7P+K9oZfCg2rD5pA=
security.jwt.expiration-time=3600000

# ====== GOOGLE OAUTH2 ======
spring.security.oauth2.client.registration.google.client-id=418023240864-ab1snvb3loio7dllf4pnc1l2hagv72ep.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
